### ISSUE TITLE
Assets missing from Sendroid_Chrome

### ISSUE THREAD

**Issue by ab** [Atekihcan/Sendroid#6]
Any plans to make the Chrome app able to run as an unpacked extension out of the box? (Hoping to be able to verify the source code of the actual Chrome extension that's running in my browser.)

It looks like the whole `data/assets` directory is missing from the git repository, along with the images that it's supposed to contain.

**Comment by Atekihcan** [comment]
Unfortunately I have no plans to work on this project anytime soon. As far as I can remember except image assets and the GCM APIkey, everything is uploaded here. I'll accept your merge request for adding the image assets. You should be able to run the Chrome app as unpacked extension with that. However, the won't communicate with the Android app as GCM API key is missing. You can register for that and a get key from Google. However, I think they have shifted to FCM now. I wish to rewrite the whole thing some day using FCM as well as add new features.
